import CLIENT_STATUS from "./clientStatus";
const CLIENT_WORKFLOW = {
  [CLIENT_STATUS.LEAD]: [CLIENT_STATUS.CONTACTED],
  [CLIENT_STATUS.CONTACTED]: [CLIENT_STATUS.QUALIFIED],
  [CLIENT_STATUS.QUALIFIED]: [CLIENT_STATUS.PROPOSAL_SENT],
  [CLIENT_STATUS.PROPOSAL_SENT]: [CLIENT_STATUS.APPROVED],
  [CLIENT_STATUS.APPROVED]: [CLIENT_STATUS.ONBOARDED, CLIENT_STATUS.SUSPENDED],
  [CLIENT_STATUS.ONBOARDED]: [CLIENT_STATUS.SUSPENDED],
  [CLIENT_STATUS.SUSPENDED]: [CLIENT_STATUS.ONBOARDED, CLIENT_STATUS.ARCHIVED],
  [CLIENT_STATUS.ARCHIVED]: [],
};

export default CLIENT_WORKFLOW;