export const ROLES = {
  ADMIN: "admin",
  MANAGER: "manager",
  VIEWER: "viewer",
};

export const PERMISSIONS = {
  CREATE_CLIENT: [ROLES.ADMIN, ROLES.MANAGER],
  EDIT_CLIENT: [ROLES.ADMIN, ROLES.MANAGER],
  DELETE_CLIENT: [ROLES.ADMIN],
  VIEW_CLIENTS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.VIEWER],
};
