const CLIENT_STATUS = {
  LEAD: "LEAD",
  CONTACTED: "CONTACTED",
  QUALIFIED: "QUALIFIED",
  PROPOSAL_SENT: "PROPOSAL_SENT",
  APPROVED: "APPROVED",
  ONBOARDED: "ONBOARDED",
  SUSPENDED: "SUSPENDED",
  ARCHIVED: "ARCHIVED",
};

module.exports = {
  CLIENT_STATUS,
};
