const { PERMISSIONS } = require("./permissions");

const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.CLIENT_CREATE,
    PERMISSIONS.CLIENT_EDIT,
    PERMISSIONS.CLIENT_DELETE,
    PERMISSIONS.CLIENT_VIEW,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USER_ROLE_UPDATE,
    PERMISSIONS.USER_STATUS_UPDATE,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.MASTER_MANAGE,
    PERMISSIONS.MASTER_VIEW,
  ],

  manager: [
    PERMISSIONS.CLIENT_CREATE,
    PERMISSIONS.CLIENT_EDIT,
    PERMISSIONS.CLIENT_VIEW,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.MASTER_MANAGE,
    PERMISSIONS.MASTER_VIEW,
  ],
  viewer: [
    PERMISSIONS.CLIENT_VIEW,
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.MASTER_VIEW,
  ],
};

module.exports = {
  ROLE_PERMISSIONS,
};
